# Generated by Django 4.0.3 on 2022-04-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder1', '0002_modelo3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo1',
            name='apellido',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='modelo2',
            name='apellido',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='modelo3',
            name='apellido',
            field=models.CharField(max_length=10),
        ),
    ]
